language: java
jdk: oraclejdk8

addons:
  sonarcloud:
    organization: "bartdebever-github"
    token": "$SONAR_TOKEN"

install:
  - cd Backend/twetter
script:
 - ./mvnw clean install -B
 - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
